name: Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - 'schema/proto/**'

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: api
  ECS_CLUSTER: poc-cluster
  ECS_SERVICE: poc-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Generate gRPC stubs (buf generate)
        working-directory: .
        run: |
          buf generate
          git status --porcelain
          # 生成差分があってもエラーにはしない（コンテナビルド時に利用するため）

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Format
        run: make fmt

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: server

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $REGISTRY/$ECR_REPOSITORY:latest
          docker push $REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
